### ISSUE TITLE
Some pages do get wrong vertical height of archived page

### ISSUE THREAD

**Issue by Gozala** [inkandswitch/xcrpt#1]
It looks like https://notes.andymatuschak.org/About_these_notes gets a wrong height as seen in this excerpt:

https://ipfs.io/ipfs/QmQnW4pKAN2tSLHgCGojHkeT72N97JFx8b9zQsmJ34qBSi/

Presumably that is because we capture height `onload` event at which point it seems to be `44px`, I'm guessing height is changed a bit later although I don't exactly know why, given no presence of JS I don't see how it comes to be.

**Comment by Gozala** [comment]
I think it is worth considering alternative where excerpt is inserted into freeze dried page instead. In my tests doing something along the following lines:

```css
body {
  transform: translateY(100vh)
}

#excerpt {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  transform: translateY(-100vh);
}
```

Works relatively well. However issues arise if #excerpt overflows (it definitely will on mobile). Finding a way to do it without absolute positioning would be ideal.
